name: Build RNNoise DLL For Windows x64

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up MSYS2 with mingw64
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-toolchain
          make
          cmake

    - name: Add mingw64 to PATH
      run: echo "::add-path::C:/msys64/mingw64/bin"

    - name: Build RNNoise DLL
      run: |
        mkdir build
        cd build
        cmake -G "MSYS Makefiles" -DCMAKE_SYSTEM_NAME=Windows ..
        make

    - name: Upload RNNoise DLL
      uses: actions/upload-artifact@v4
      with:
        name: rnnoise-dll
        path: build/librnnoise.dll
